# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ feature/sync2sdk ]
  pull_request:
    branches: [ feature/sync2sdk ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run:  apk add ruby && gem install mustache
#      - name: creates output
#        run:  sh ./build.sh
      - name: Pushes to another repository
        id: push_directory
        uses: conggeqc/github-action-push-to-another-repository@feature/sync2sdk
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          #source-directory: output/
          #destination-github-username: 'conggeqc'
          #destination-repository-name: 'test'
          user-email: conggeqc@gmail.com
          user-name: conggeqc
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          #target-branch: api-specs-sync
          api-specs-github-username: 'conggeqc'
          api-specs-repository-name: 'qingcloud-api-specs'
          api-specs-target-branch: master
          java-sdk-github-username: 'conggeqc'
          java-sdk-repository-name: 'qingcloud-sdk-java'
          java-sdk-target-branch: api-specs-sync

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY

#      - name: Create Pull Request
#        uses: peter-evans/create-pull-request@v3
#        with:
#           token: ${{ secrets.API_TOKEN_GITHUB }}
#           commit-message: create Pull requests by robot
#           title: pr by robot
#           body: create Pull requests from branch api-specs-sync by robot
#           branch: master
#           base: master


